[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

# Redirect domain aliases to primary domain
[[redirects]]
  from = "https://somethingaboutmusic.blog/*"
  to = "https://www.somethingaboutmusic.blog/:splat"
  status = 301
  force = true

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://somethingaboutmusic.netlify.app/*"
  to = "https://www.somethingaboutmusic.blog/:splat"
  status = 301
  force = true