[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect domain aliases to primary domain
[[redirects]]
  from = "https://somethingaboutmusic.blog/*"
  to = "https://www.somethingaboutmusic.blog/:splat"
  status = 301
  force = true

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://somethingaboutmusic.netlify.app/*"
  to = "https://www.somethingaboutmusic.blog/:splat"
  status = 301
  force = true

# Handle static file routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200